CREATE TABLE adopt 
(male VARCHAR(20) NOT NULL, 
mage INT NOT NULL, 
female VARCHAR(20) NOT NULL, 
fage INT NOT NULL, 
address VARCHAR(30) NOT NULL,
 email VARCHAR(30) NOT NULL, 
tno INT,
 mno INT NOT NULL,
 mprofession VARCHAR(20) NOT NULL,
 mm INT NOT NULL,
 fprofession VARCHAR(20) NOT NULL,
 fm INT NOT NULL, 
reason VARCHAR(100) NOT NULL, 
PRIMARY KEY (email));

