CREATE TABLE ngo 
(ngoid INT NOT NULL, `
state` VARCHAR(255) NOT NULL,
 district VARCHAR(255) NOT NULL,
 regno INT NOT NULL,
 noo VARCHAR(255) NOT NULL, 
email VARCHAR(255) NOT NULL,
 password VARCHAR(255) NOT NULL,
 phno INT NOT NULL, 
address VARCHAR(255) NOT NULL, 
acti VARCHAR(255) NOT NULL,
 PRIMARY KEY (ngoid, email));

