CREATE TABLE `user` 
(`NAME` VARCHAR(30) NOT NULL,
 `ADDRESS` VARCHAR(30) NOT NULL,
 `GENDER` VARCHAR(60) NOT NULL,
 `AGE` VARCHAR(10) NOT NULL, 
`CONTACT` VARCHAR(30) NOT NULL, 
`EMAIL` VARCHAR(30) NOT NULL, 
`USER_ID` VARCHAR(30) NOT NULL, 
`PASSWORD` VARCHAR(30) NOT NULL,
 PRIMARY KEY (`EMAIL`));

